gruntwork-io/helm-kubernetes-services

CONTRIBUTING.md, README.md
After prototyping and reading some documents on how to develop helm charts, I landed on these set of guidelines for chart development.
The tl;dr is:
- Make sure you follow [the official best practices on chart development](https://docs.helm.sh/chart_best_practices/)
- Don't provide defaults in `values.yaml` for required inputs
- Use `linter_values.yaml` for required inputs compatible with `helm lint` (see https://github.com/gruntwork-io/pre-commit/#linter_valuesyaml for an explanation).
- Document values, even more than the official guide recommends.
- There are two sets of tests for every helm chart: helm tests and terratests
- helm tests are run by helm, and is used to check the deployment. This means that these tests are meant to be run in production to validate the chart install.
- …
=> RDD: Some initial guidelines on chart development

.circleci/config.yml, charts/k8s-service/templates/ingress.yaml, charts/k8s-service/values.yaml, test/Gopkg.lock, test/Gopkg.toml, test/k8s_service_example_test_helpers.go, test/k8s_service_nginx_example_test.go
__~This depends on https://github.com/gruntwork-io/terratest/pull/273 and https://github.com/gruntwork-io/module-ci/pull/91~ Both are merged and PR is updated to point to released versions__
This fixes several bugs found in the `Ingress` resource template:
- The API group is `extensions/v1beta1`.
- There was a typo in one of the if conditions.
- The rules required setting a `host`, but sometimes you want the ingress to match all hosts. This supports that.
To flush these bugs out, I implemented a test that verifies that the chart correctly provisions an ingress resource and that you can access a service using the ingress endpoint.
=> Fix Ingress bugs

charts/k8s-service/README.md, charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
This adds support for rendering in `imagePullSecrets` to the pod spec of the deployment so that we can support private registries.
See https://kubernetes.io/docs/concepts/containers/images/#using-a-private-registry for more info
=> Support image pull secrets

charts/k8s-service/README.md, charts/k8s-service/templates/ingress.yaml, charts/k8s-service/values.yaml, test/Gopkg.lock, test/Gopkg.toml, test/k8s_service_example_test_helpers.go, test/k8s_service_nginx_example_test.go, test/k8s_service_template_render_helpers_for_test.go, test/k8s_service_template_test.go
Sometimes it is desirable to add additional path rules to the ingress resource. For example, if you wanted a HTTP => HTTPS redirect rule with the ALB ingress controller, you need to create a special catch all path that does the redirect (see https://kubernetes-sigs.github.io/aws-alb-ingress-controller/guide/tasks/ssl_redirect/). This path needs to be injected before the application service path. Or you might want to create a route for a side car container that is deployed in the service.
To support these use cases, this PR introduces two new input values `additionalPaths` and `additionalPathsHigherPriority` that can be used to inject additional path rules to the ingress resource.
=> Enable setting additional paths on ingress

charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
This adds the ability to set a custom command on the container in the Deployment. This is useful if you are trying to deploy a simple service, like a port forwarder using `nc`.
=> Add ability to set container command

charts/k8s-service/templates/gmc.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
This PR makes the certificate name configurable. As the certificate name needs to be referenced in the ingress, users of the chart need full control over the name of the certificate. Now the name was the `fullName`, which meant that the chart user wouldn't know the name without reading the chart source code.
=> Make cert name configurable

charts/k8s-service/templates/ingress.yaml, test/k8s_service_template_test.go
This PR fixes issue https://github.com/gruntwork-io/helm-kubernetes-services/issues/34
Rendered template after fix
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
name: release-name-test-app
labels:
gruntwork.io/app-name: test-app
app.kubernetes.io/name: test-app
helm.sh/chart: k8s-service-0.0.1-replace
app.kubernetes.io/instance: release-name
app.kubernetes.io/managed-by: Tiller
spec:
tls:
- hosts:
- test-app.com
secretName: test-app-tls
rules:
- host: "test-app.com"
http:
paths:
- path: /
backend:
serviceName: release-name-test-app
servicePort: 80
```
=> Fixed Ingress TLS template issue

charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
Support for securityContext per the request [Issue #26 ](https://github.com/gruntwork-io/helm-kubernetes-services/issues/26)
Test cases added and passing;
```
=== RUN   TestK8SServiceSecurityContextAnnotationRenderCorrectly
=== PAUSE TestK8SServiceSecurityContextAnnotationRenderCorrectly
=== CONT  TestK8SServiceSecurityContextAnnotationRenderCorrectly
TestK8SServiceSecurityContextAnnotationRenderCorrectly 2019-08-28T09:06:54+05:30 command.go:87: Running command helm with args [template --set securityContext.privileged=true --set securityContext.runAsUser=1000 -f /home/shenal/go/src/helm-kubernetes-services/charts/k8s-service/linter_values.yaml -x templates/deployment.yaml /home/shenal/go/src/helm-kubernetes-services/charts/k8s-service] …
```
=> Added support for Security Context

charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
This adds support for injecting the required annotations to the pod spec for the deployment to project the Service Account token into IAM credentials using IRSA. You can read more about the spec in the blog post for [IAM Roles for Service Accounts](https://aws.amazon.com/blogs/opensource/introducing-fine-grained-iam-roles-service-accounts/).
=> Add IRSA injection

charts/k8s-service/templates/deployment.yaml, charts/k8s-service/templates/ingress.yaml, test/k8s_service_template_test.go
This PR fixes:
- https://github.com/gruntwork-io/helm-kubernetes-services/issues/40: `sideCarContainers` did not render correctly in the deployment
- https://github.com/gruntwork-io/helm-kubernetes-services/issues/37: `additionalPaths` and `additionalPathsHigherPriority` required a `serviceName` when using with `hosts`.
Added regression tests for each case to ensure the issue is actually fixed.
=> Fix sidecar and additionalpaths rendering

charts/k8s-service/README.md, charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_service_account_template_test.go, test/k8s_service_template_test.go
- Allow setting a different service account on the Pod
- Allow disabling the default ports that are exposed
- Update README to include information on how to deploy a worker service
- Update values docs to link to `secrets` from the `envVars` settings.
=> Improvements to k8s-service

charts/k8s-service/README.md, charts/k8s-service/templates/horizontalpodautoscaler.yaml, charts/k8s-service/values.yaml, test/k8s_service_horizontal_pod_autoscaler_template_test.go
This PR will resolve issue #48 by adding the template for horizontal pod autoscaler with for the time being the cpu and memory resources. The other option is to allow the user to supply the whole metrics block but this is a start
=> feat: issue 48 adding Horizontal Pod Autoscaler resource

README.adoc
This link was a 404. Removing as discussed in: https://gruntwork-io.slack.com/archives/C76UJFUEL/p1579624661058000?thread_ts=1579539740.041000&cid=C76UJFUEL
=> Remove link to faq

README.adoc
How to download the charts are no longer visible after the recent README updates, so added back in a link to `helmcharts.gruntwork.io` at the top.
=> [skip ci] Add mention of where to get charts at top of README

.circleci/config.yml
The deploy script failed on `v0.1.1`, and it was because `--save` is no longer a valid option.
=> Remove --save on helm package since it was removed in helm 3

charts/k8s-service/templates/deployment.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
RE: https://github.com/gruntwork-io/helm-kubernetes-services/issues/74
Added two arguments to the values template and in the deployment to allow a user to add additional labels to their pod and deployment. These are provided by additionalDeploymentLabels:{} and additionalPodLabels:{} that the user can provide a map to the same as the annotations arguments. 
I was contemplating adding something to the matchLabels as well but I felt that might open up a can of worms with the core functionality of the template providing a single deployment so I left that in the end.
The main aim is to allow users to integrate gruntwork templates with other labelling schemes they would be running in their k8s workload as well as the mentioned use case in the issue where labels are required for certain tagging …
=> Surfacing Additional Pod Labels for user

.circleci/config.yml
Fix install helm step in build where it is installing the stable repo from the wrong place.
=> Fix helm stable repo

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_config_injection_example_test.go, test/k8s_service_example_test_helpers.go, test/k8s_service_nginx_example_test.go, test/k8s_service_template_test.go, test/k8s_service_volume_template_test.go, test/k8s_service_volume_test.go
This implements a new feature that allows you to mount `tmpfs` volumes to arbitrary paths in your container. See the docs for `scratchPaths` input value for more info on the semantics.
This uses the `emptyDir` volume [in kubernetes](https://kubernetes.io/docs/concepts/storage/volumes/#emptydir).
=> Add feature to mount tmpfs volumes

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
Fixes #64
Based on https://github.com/gruntwork-io/helm-kubernetes-services/pull/84, the changes suggested in that PR are implemented here with appropriate updated tests.
[Gist showing test output](https://gist.github.com/amirha97/e623fa737ea9e693080ae6b88cc3ec39)
=> Add support for customising deployment strategy

charts/k8s-service/templates/_helpers.tpl, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
There's no current way to explicitly define the fullname that appears in deployments, services, etc.  Given that a user may want this ability, particularly if they are running multiple k8s-services in the same cluster.  This pull request enables users to override the fullname through the `fullnameOverride` key.
=> allows for the fullname to be overidden in the values

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_volume_template_test.go
Resolves #105, adding support for node backed `emptyDirs`. 
I have added the `emptyDirs` input to `values.yaml`, which takes a map of volume name to mount path. 
I used the new input instead of changing the existing `scratchPaths` input to ensure backwards compatibility.
I have configured the template such that each `emptyDir` volume has the configuration:
https://github.com/gruntwork-io/helm-kubernetes-services/blob/91e901bf035871f3df9c388d3504b5c3bfe8d32d/charts/k8s-service/templates/_deployment_spec.tpl#L390-L393
I could also set it up so that the user could pass the emptyDir configuration through themselves as part of the map.
=> feat: add support node backed emptyDirs

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_volume_template_test.go
Adding the terminationGracePeriodSeconds option to enable configuration for time the pod needs to shut down before deletion.
Kubernetes API documentation: https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#pod-v1-core
A [PR](https://github.com/gruntwork-io/helm-kubernetes-services/pull/102) of the same changes was raised by [Megan](https://github.com/meganjohn) but as she is now on leave we're unable to updated the original PR. As a consequence we have raised another to cover the original changes and address the comments (update values.yaml and add a template test).
Apologies for the confusion and let me know if there are any issues.
=> Adding termination grace period logic

charts/k8s-service/templates/_capabilities_helpers.tpl, charts/k8s-service/templates/ingress.yaml, charts/k8s-service/templates/pdb.yaml, charts/k8s-service/values.yaml, test/go.sum, test/k8s_service_template_test.go
This allows the `k8s-service` chart to be more flexible in targeting different Kubernetes versions, while still avoiding deprecated interfaces. For example, `PodDisruptionBudget` was located in `policy/v1beta1`, but has been moved to `policy/v1`, and the version in `policy/v1beta1` is now marked for deprecation since k8s 1.21. If the helm chart is being installed to a k8s cluster <1.21, then it is preferred to use `policy/v1beta1`, while targeting k8s cluster >=1.21 requires using `policy/v1`. To support this, we can introspect the `Capabilities` built in object to get metadata about the target k8s cluster, and select the right version to use based on that.
This PR addresses this kind of API discrepancy for `Ingress` and `PodDisruptionBudget` resources.
=> Use capabilities introspection to know which API version should be targeted for the resources

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_lifecycle_hooks_template_test.go, test/k8s_service_template_test.go
This adds the ability to configure a custom lifecycle hook on the main application container, in a way that works nicely with the existing `shutdownDelay` input value.
=> Add support for explicitly setting lifecycle hooks

charts/k8s-service/templates/service.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_render_helpers_for_test.go, test/k8s_service_template_test.go
This change adds k8s service support for `sessionAffinity` and `sessionAffinityConfig` as defined in Kubernetes ([here](https://kubernetes.io/docs/concepts/services-networking/service/#virtual-ips-and-service-proxies)):
> "If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting service.spec.sessionAffinity to "ClientIP" (the default is "None"). You can also set the maximum session sticky time by setting service.spec.sessionAffinityConfig.clientIP.timeoutSeconds appropriately. (the default value is 10800, which works out to be 3 hours)."
Configuration has been documented in the [values.yaml](https://github.com/gruntwork-io/helm-kubernetes-services/pull/124/files …
=> Add support for service sessionAffinity

charts/k8s-service/templates/_capabilities_helpers.tpl, test/fixtures/ingress_values_with_name_port.yaml, test/fixtures/ingress_values_with_number_port.yaml, test/k8s_service_template_render_helpers_for_test.go, test/k8s_service_template_test.go
This PR fixes a bug where the number type checking for ingress port expression isn't good enough when passing through a number with `values.yaml`. `helm` seems to coerce numbers into strings when going through a `values.yaml` file, which doesn't happen when using `--set`.
This PR also adds a regression test to make sure we test the path with `values.yaml`.
The regression test expectedly fails without the fix in adc83736d7b09d6332d5350d37dd0fb9d3b783b8 (see build https://app.circleci.com/pipelines/github/gruntwork-io/helm-kubernetes-services/343/workflows/8e969b8a-2c9e-4b1f-819d-e15fb52ff958), but passes after the fix (see https://app.circleci.com/pipelines/github/gruntwork-io/helm-kubernetes-services/344/workflows/a0eeb12e-f372-4005-894b-0e54d3843364)
Please ensure all of these TODOs are …
=> Ingress port number type conversion issue

.circleci/config.yml, test/go.mod, test/go.sum, test/k8s_service_nginx_example_test.go
This updates the machine image from the deprecated ubuntu 16.04 based image to ubuntu 20.04.
This also updates the docker image from the deprecated `circleci` images to `cimg`.
Please ensure all of these TODOs are completed before asking for a review.
=> Bump machine and docker images

charts/k8s-service/README.md
Add documentation for mounting volumes on sidecar and init containers. 
README
Please ensure all of these TODOs are completed before asking for a review.
=> Documentation for mounting volumes on sidecar or init containers

charts/k8s-service/templates/service.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go, test/k8s_service_volume_test.go
Title saids it all
Added support for configuring cluster ip on service. This will allow you to configure a [headless Kubernetes service](https://kubernetes.io/docs/concepts/services-networking/service/#headless-services).
=> Added support for configuring cluster ip on service

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
Enables support for custom args on deployment spec. The current helm only allows custom commands, making it hard to reuse the image by changing the args only and keeping the command (ENTRYPOINT).
It is supported by Kubernetes, for reference: https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/#use-environment-variables-to-define-arguments.
Gist with [template tests](https://gist.github.com/thiagosalvatore/e02bb81f610d5003fe5f1382b9487188)
Implements #142 
Added / Removed / Updated [X].
[X] - Added new input parameter `containerArgs` that can be used to define custom args that should be passed to the deployment …
=> Allow custom args on deployment spec

charts/k8s-service/templates/service.yaml, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
Update `k8s-service` helm chart to allow configuration of traffic policies for created K8S service
Added / Removed / Updated [X].
=> Expose traffic policy configuration for service

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_config_injection_template_test.go
Add support for subPath in secrets volumes, same way as already possible for configMaps.
Added / Removed / Updated [X].
=> Add support for subPath in secrets volumes

charts/k8s-service/README.md, charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_template_test.go
Adds support for `hostAliases`, as per #111 
It was necessary to make the configuration a list, since a map has non-deterministic ordering and order is important in the `/etc/hosts` file.
I also fixed a couple small typos I came across in docs.
Let me know if you want anything changed!
Added support for hostAliases in pod template
=> Add support for hostAliases in pod templates

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_config_injection_template_test.go
Fixes #159.
This PR introduces suport for [priorityClassName](https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#pod-priority) and adds the `TestK8sServicePriorityClassName` test.
*documented in values.yaml. I'm happy to add something to `/charts/k8s-service/README.md` if that is determined to be necessary.
Added support for priorityClassName.
=> Add priorityclassname Support and Test

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml
Fixes #164 by adding support for [Startup Probes](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/).
Added support for Startup Probes
=> Add support for Startup Probes

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml
Adds support for dnsPolicy. Fixes #173.
dnsPolicy has been added to the values.yaml file under Optional Values. If set, it will add it to the deployment spec section.
Added / Removed / Updated [X].
Added dnsPolicy to the values.yaml. If present it will get added to the deployment spec section.
=> add support for dnsPolicy

README.adoc, charts/k8s-service/README.md, charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml, test/k8s_service_config_injection_template_test.go, test/k8s_service_template_test.go, test/k8s_service_volume_secret_store_csi_template_test.go
Fixes #171 . Can be considered part (subtask) of #118 
In the deployment_spec.tpl we must allow a new "**as**" value to be passed to a secret block, we call this new type "csi".
Receiving this type of a secret, the tpl has to mix functionality of both volumes and environment types, as we will require a env block and a volumeMounts block
Allow secret of type csi, inject Secret Store CSI related fields to deployment spec Env and Volumes
=> 171 inject Secret Store CSI driver `deployment_spec.tpl`

charts/k8s-service/templates/_deployment_spec.tpl, test/k8s_service_template_test.go
Setting a replica number if HPA is used can cause outages (if `replicas is 0`) or degraded performance if `replicas < minReplicas`
One thing to note: The canary deployment is not targeted by the HPA:
* The name of the canary has `-canary` at the end see [code](https://github.com/gruntwork-io/helm-kubernetes-services/blob/main/charts/k8s-service/templates/_deployment_spec.tpl#L83)
* The HPA target focuses on the main deployment only [see code ](https://github.com/gruntwork-io/helm-kubernetes-services/blob/main/charts/k8s-service/templates/horizontalpodautoscaler.yaml#L11)
So we need to avoid the `replicas` only if the deployment is not a canary.
Fixes #180.
Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691 …
=> Avoid setting replicase while HPA is enabled

charts/k8s-service/templates/_deployment_spec.tpl, charts/k8s-service/values.yaml
Fixes #74 when deploying via ArgoCD, which surfaces this issue with string encapsulation of boolean values for labels: https://github.com/argoproj/argo-cd/issues/4391
This shouldn't create any backwards compatibility issues.
=> fix: additional pod/deployment labeling bool string encapsulation
